### ISSUE TITLE
To many Medicine Men

### ISSUE THREAD

**Issue by Hexblood** [TeamTotemic/Totemic#106]
Minecraft version: 1.12.2
Forge version: 14.23.5.2836
Totemic version: 1.12.2-0.11.6

Issue: 
The weight of the Medicine Men is very high. Exploring worlds on a few versions of the mod have yielded the same result. Villages are half or more made up of Medicine Men. This is throwing off access to Vanilla Villagers.

Suggested fix:
Limit Medicine Man spawns to 1-2 per village and/or give a config setting to adjust the spawn chance of Medicine Men.

**Comment by ljfa-ag** [comment]
I can't directly adjust the spawn rates of Medicine Men, since the villager profession is chosen uniformly randomly. The problem is probably that Medicine Wheels and Tipis always spawn a Medicine Man.
I will probably not be changing this for the 1.12 version soon. The workaround would be to disable spawning of Tipis and Medicine Wheels in the config.

**Comment by ljfa-ag** [comment]
I changed my mind, I will be addressing this by not (solely) spawning Medicine Men in Tipis and Medicine Wheels.

**Comment by ljfa-ag** [comment]
Some investigation yielded that after removing the Medicine Men spawns from Totemic's village structures, the villages are still mostly made up of Medicine Men. The RNG used to choose random villager professions seems to always return the same value. I can't figure why this is happening but it might actually be a Forge bug.

**Comment by ljfa-ag** [comment]
I made an attempt to solve the underlying issue, the fix can be activated with a config option. Or, Medicine Men can be disabled in the config altogether.
