### ISSUE TITLE
Bug: Stacking Buffs to near infinity

### ISSUE THREAD

**Issue by SirAron111** [TeamTotemic/Totemic#107]
There seems to be a bug related to how the Totem poles and the Medicine bag act together.

Entering and exiting the area of a active Totem pole and with a bag that is bound to it will stack up the buff so instead of the Cow totem giving the Intended Slow 1 and Resistance 1 with the bag bound to it having it open and going into the Poles Area of effect and out again, during combat this happens multiple times, The Resistance and Slowness Start to stack up so you suddenly get Resistance 2 than resistance 3 sometimes the buff stays until relogging.

You can basically get the infamous Resistance up to being unkillable and the slowness up to being unable to move.
This also happens with other buffs as i tested.

This is very bothersome as I have found during testing it myself and from player reports.

**Comment by SirAron111** [comment]
![2019-08-08_21 51 31](https://user-images.githubusercontent.com/39855956/62733583-38be5780-ba27-11e9-8164-f19b67fc0303.png)
![2019-08-08_21 53 57](https://user-images.githubusercontent.com/39855956/62733584-38be5780-ba27-11e9-9290-e22258d2807f.png)
The buff bag saves the resistance 4 which is super broken. And the totems themselves are to strong as well is there no way to make the totem poles cost ingreatient when creating them. For example the blaze one needs a blaze rod in offhand to make etc.
But what It really needs is a config setting to cap the stacking effects to a certain amount for example only one stack or non at all. As well as the fix of the buff bag infinite stacking
Having everlasting abiltiys will make ou not even need the totems poles or bags anymroe since they refresh the stacked buffs as well. running around beeing imortal at resist 5 is to op

**Comment by VincentLongiug** [comment]
I didn't understood what you meant until I saw the images : I've only built 1 Totem without duplicates for now, that may be why I didn't encountered your bug. I'll try with more and come back to you if I got the same.
About the fact that Totems should need an "activator" or something before granting a Buff, I think I've got a pretty good suggestion. But I wait for the devs to tell me if they have a ToDo list : I don't want to write a pile of text if they're already working on it (or if they already said they don't want it)
... but I don't want to wait for too long either !

**Edit :** OK, I got it. I think the "stacking Buff" you talked about was made on purpose : a Totem which has 1 Pole of a kind gives you a Buff, if it has 3 Poles of a kind, the Buff gains 1 LV and with 5 Poles of a kind, it gains 2 LV (it does not happen for every Buff, but clearly most of them, that's why you can have Resistance IV and only get Slowness I (and not III) in counterpart).
So the Buffs will never stack to infinity because you can only have 5 Poles on 1 Base and because Poles on differents Bases don't stack their Buff together.
Besides, I didn't noticed interferences between the Totems and the Medicine Bag : the Bag only stores the Buff of 1 Pole, but if the Buff granted is upgraded thanks to duplicates on the same Totem, the upgrade won't be stored.
About the "everlasting abilities", I don't really understand what you mean and how you got it : for what I've experienced, the Buffs are granted for only 5 seconds (with a few exceptions) and refreshed only if you are in a 6 blocks range of the corresponding Totem and/or if you have a corresponding Medicine Bag open (which deplete slowly if you're away from its referent Pole).
Can you explain me the circumstances that gave you "everlasting abilities" ?

**Comment by SirAron111** [comment]
@VincentLongiug The thing with the medicine bag its hat it refreshes the current buff you have so if you have resistance 4 from the totem poles and the bag is attuned to the cow basically it would give you resist 2 at most but if you keep it open after exiting the area of resistance 4 totem pole you keep resistance 4 as it refreshes the buff you have doesn’t update to the lower version once the upper version runs out.

As for everlasting abilities it’s a another mod that lets you equip permanent effects (for example resistance 1 is a rare one) but if you have that and pass by the resistance 4 totem pole and exit the area since the ability gets refreshed from the everlasting one tiring to refresh its resistance 1 it keeps refreshing the resistance 4 from the totem pole. This mod isn’t getting well maintained I think I will remove it from my pack I made another post months ago didn’t even get a response there.

I was hopeing there would be a config at some point to limit the totems effects so I can say you get resistance 1 at most even if you stack poles. Currently it’s just broken getting resistance 4 is like 20%*4 damage reduction. Completely goes overbalance in combat packs if someone get a medicine bag stacks up some cow and goes unkillable for some time.

Also on big packs not being able to lower the difficulty of the last rituals (which are impossible to do even with a small lag spike) makes it to hard for players on hardmode (which is force set for the pack. as the totem mod scales with hardmode and easy mode -.-)

**Comment by VincentLongiug** [comment]
No response for months ! Seriously ?! I hope they're not on permanent vacations : this mod is still in 0.X and has too much potential to die now !
*Last acivity of a dev on GitHub : 4 July. We have hope (?)*

Well, I'm only beginning playing with Totemic, so I can't complain about the difficulty of certain Ceremonies since I haven't perform any of them yet. 

About the Medicine Bag, I can assure you that it refreshes a Resistance II when you go away from your 5 Cow Poles Totem. Maybe Everlasting Abilities is responsible of this impression... and maybe the way this mod has to grant Buffs just don't fit with Everlasting since it can give you stacked Buffs near Totems and normal Buffs on demand away from them (which is also kindda OP).
I don't think it's a bad thing that we have a possibility to get stacked Buffs (I mean, we have no obligation to get them if we don't want to, and admins on modded PvP servers can forbid their (abusive) use), but I agree that it's way too easy to get them : we're able to build a Totem within 10 min of game and a Pole on a Base grants a permanent Buff in the nearby area by default...

\**cracks his fingers*\*
Stay tuned my friend, I'm coming with a little something ...

**Edit :** I tested Ceremonies a bit... it's basicly :
>Hold Right Click with a Flute in your left hand and a Rattle in your right one while running around the Drums wearing a Jingle Dress.

and **NO !** even with Wind Chimes and when I change the Flute for the Whistle in the middle, it seems I don't have enough unique Instruments to perform the 5🎵 Ceremonies : I reach the Threshold of everything ***right*** before having enough Melody 😤. 
![2019-08-09_22 01 04](https://user-images.githubusercontent.com/52882424/62805829-6e2f7780-baf1-11e9-809d-fcce19b26c43.png)

Maybe we'll have to wait until the Netherumbrian Pipes are fully implemented to achieve them (or maybe my sync with Wind Chimes is awful)...

**Edit 2 :** My bad : Wind Chimes hanging on Leaves provides more Melody. I managed to perform some 5🎵 Ceremonies without struggling thanks to that.
