### ISSUE TITLE
Add decorative pillar block that looks like the old totem poles

### ISSUE THREAD

**Issue by ljfa-ag** [TeamTotemic/Totemic#84]
As per request, since some players were using totem poles like that and the addition of the new models broke the aesthetic.

**Comment by Carnaxus** [comment]
Speaking of which, is there a reason the new models just look like shrunk-down tree logs instead of having *any* way to tell which totems they are?  Or is that an Optifine bug that I'm just not aware of?

**Edit:** Never mind, I saw there was talk of a change in the models and didn't get which came first.  My bad.
