### ISSUE TITLE
Collection of feature ideas

### ISSUE THREAD

**Issue by angelnc1989** [TeamTotemic/Totemic#90]
- Canoe: 
  - a canoe with similar functionality to the vanilla Minecraft Boat
- Tomahawk: 
   - as a weapon and axe
   - maybe throwable
- Buffalo Hide armor: 
   - posssibly with a set bonus
   - chieftain headdress made out of Eagle Feathers
   - moccasin
- Dream Catcher:
  - boosting Melody power
- Corn crop
- Firepit:
  - might be used to cook food
- Horse rug:
   - as alternative to the vanilla saddle
- More decoration options:  
   - Red Cedar Stairs
   - Red Cedar Slab
   - Red Cedar Fence
   - Red Cedar Fence Gate
   - Red Cedar Door
   - Drum with different woods as bases
   - Totem Torch with different woods as bases
- Mod integration: 
   - Red Cedar Chest/Trapdoor/Bookshelf when [Quark](https://minecraft.curseforge.com/projects/quark) is installed
  - Tall Red Cedar Fence Gate when [TallGates](https://minecraft.curseforge.com/projects/tallgates?gameCategorySlug=mc-mods&projectID=283913) is installed
  - Red Cedar Storage Drawer variants when [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers?gameCategorySlug=mc-mods&projectID=223852) is installed
- [Botania](https://minecraft.curseforge.com/projects/botania?gameCategorySlug=mc-mods&projectID=225643): Ceremony that generates a burst of mana

**Comment by ljfa-ag** [comment]
Alright, sorry for not answering this for so long.

We probably won't add things that are essentially copies of vanilla stuff like boats and saddles.
Tomahawks seem to be pretty inconvenient to use in practice, based on my experience with another mod that adds throwable Tomahawks.
Dream catchers: I think there used to be plans of having them in Tipis. Might look into that.
Red Cedar decorations have been added recently.
Mod integration: Doesn't seem to be easily possible in some cases (like TallGates). Otherwise I would rather become more familiar with mods that I add integration for.
